SoftkitWeb/Controllers/CotizadorController.cs
using Microsoft.AspNetCore.Mvc;
using RESTAPI_CORE.Modelos;
using SoftkitWeb.Models;
using SoftkitWeb.Utilitarios;
 
namespace SoftkitWeb.Controllers
{
    public class CotizadorController : Controller
    {
        private readonly ILogger<CotizadorController> _logger;
        private readonly MetodosApis _metodosApis;

        public CotizadorController(ILogger<CotizadorController> logger, MetodosApis metodosApis)
        {
            _logger = logger;
            _metodosApis = metodosApis;
        }
        public IActionResult Index()
        {
            return View();
        }

        #region Articulo
        [HttpPost]
        public async Task<IActionResult> ListarArticulos(string descripcion)
        {
            var apiUrl = string.Format("Articulo/ListaArticulo?descripcion={0}", descripcion ?? "");
            var result = await _metodosApis.GetAsync<Response<List<Articulo>>>(apiUrl);
            return Json(result);
        }

        #endregion

        #region Cliente
        [HttpGet]
        public async Task<IActionResult> ListarCliente()
        {
            var apiUrl = "Cliente/Lista";
            var result = await _metodosApis.GetAsync<Response<List<Cliente>>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarCliente([FromBody] Cliente obj)
        {
            var apiUrl = "Cliente/Guardar";
            var result = await _metodosApis.PostAsync<Response<string>>(apiUrl, obj);
            return Json(result);
        }

        [HttpPut]
        public async Task<IActionResult> EditarCliente([FromBody] Cliente obj)
        {
            var apiUrl = "Cliente/Editar";
            var result = await _metodosApis.PutAsync<Response<string>>(apiUrl, obj);
            return Json(result);
        }

        #endregion

        #region Cotizacion

        [HttpGet]
        public async Task<IActionResult> ListarCotizacion()
        {
            var apiUrl = "Cotizacion/Lista";
            var result = await _metodosApis.GetAsync<Response<List<CotizacionBuscar>>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> ObtenerCotizacion(int idcotizacion)
        {
            var apiUrl = string.Format("Cotizacion/Obtener/{0}", idcotizacion);
            var result = await _metodosApis.GetAsync<Response<List<Cotizacion>>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> KardexCotizacion(string codigo, string codcliente)
        {
            var apiUrl = string.Format("Cotizacion/KardexCotizacion?codigo={0}&codcliente={1}", codigo, codcliente);
            var result = await _metodosApis.GetAsync<Response<List<KardexCoti>>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> KardexVenta(string codigo, string codcliente)
        {
            var apiUrl = string.Format("Cotizacion/KardexVenta?codigo={0}&codcliente={1}", codigo, codcliente);
            var result = await _metodosApis.GetAsync<Response<List<KardexVenta>>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> KardexNotaIngreso(string codigo, string codcliente)
        {
            var apiUrl = string.Format("Cotizacion/KardexNotaIngreso?codigo={0}&codcliente={1}", codigo, codcliente);
            var result = await _metodosApis.GetAsync<Response<List<KardexNotaIngreso>>>(apiUrl);
            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> SecuenciaCoti(int codigo)
        {
            var apiUrl = string.Format("Cotizacion/SecuenciaCoti?codigo={0}", codigo);
            var result = await _metodosApis.GetAsync<Response<int>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarCotizacion(List<Cotizacion> cotizaciones)
        {
            cotizaciones.ForEach(x => x.usuario = User.Identity.Name); 
            var apiUrl = "Cotizacion/Guardar";
            var result = await _metodosApis.PostAsync<Response<string>>(apiUrl, cotizaciones);
            return Json(result);
        }

        #endregion

        #region Producto
        [HttpGet]
        public async Task<IActionResult> ListarProducto()
        {
            var apiUrl = "Producto/Lista";
            var result = await _metodosApis.GetAsync<Response<List<Producto>>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> ObtenerProducto(int idProducto)
        {
            var apiUrl = string.Format("Producto/Obtener/{0}", idProducto);
            var result = await _metodosApis.GetAsync<Response<Producto>>(apiUrl);
            return Json(result);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarProducto([FromBody] Producto obj)
        {
            var apiUrl = "Producto/Guardar";
            var result = await _metodosApis.PostAsync<Response<string>>(apiUrl, obj);
            return Json(result);
        }

        [HttpPut]
        public async Task<IActionResult> EditarProducto([FromBody] Producto obj)
        {
            var apiUrl = "Producto/Editar";
            var result = await _metodosApis.PutAsync<Response<string>>(apiUrl, obj);
            return Json(result);
        }

        [HttpDelete]
        public async Task<IActionResult> EliminarProducto(int idProducto)
        {
            var apiUrl = string.Format("Producto/Eliminar/{0}", idProducto);
            var result = await _metodosApis.DeleteAsync<Response<string>>(apiUrl);
            return Json(result);
        }

        #endregion

        #region Proveedores 
        [HttpGet]
        public async Task<IActionResult> ListarProveedores()
        {
            var apiUrl = "Proveedor/Lista";
            var result = await _metodosApis.GetAsync<Response<List<Proveedor>>>(apiUrl);
            return Json(result);
        }
        #endregion

        #region Regla

        [HttpGet]
        public async Task<IActionResult> ObtenerReglas()
        {
            var apiUrl = "Regla/Lista";
            var result = await _metodosApis.GetAsync<Response<List<Regla>>>(apiUrl);
            return Json(result);
        }

        #endregion

    }
}

SoftkitWeb/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoftkitWeb</title>


    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/fontawesome-free/css/all.min.css">

    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/lib/adminlte/dist/css/adminlte.min.css">

    <!-- daterange picker -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/daterangepicker/daterangepicker.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
    <!-- BS Stepper -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/bs-stepper/css/bs-stepper.min.css">
    <!-- dropzonejs -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/dropzone/min/dropzone.min.css">

    <!-- DataTables -->
    <link rel="stylesheet" href="~/lib/adminlte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/adminlte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/adminlte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/adminlte/plugins/datatables-select/css/select.bootstrap4.min.css" rel="stylesheet" />

    <!-- adminlte -->
    <link href="~/lib/adminlte/dist/css/adminlte.min.css" rel="stylesheet" />
    <link href="~/css/_all-skins.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown user-menu">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        <img src="~/lib/adminlte/dist/img/user2-160x160.jpg" class="user-image img-circle elevation-2" alt="User Image">
                        <span class="d-none d-md-inline"> @User.Identity.Name </span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <!-- User image -->
                        <li class="user-header bg-primary">
                            <img src="~/lib/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image"> 
                            <p>
                                @User.Identity.Name
                                <small> @User.FindFirst(ClaimTypes.Role)?.Value </small>
                            </p>
                        </li> 
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <a href="/Account/Logout" class="btn btn-default btn-flat float-right">Cerrar Sesion</a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar main-sidebar-custom sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="~/lib/adminlte/index3.html" class="brand-link">
                <img src="~/lib/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Softkit Web</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/lib/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">@User.Identity.Name</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                        <li class="nav-item menu-open">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                <i class="nav-icon fas fa-th"></i>
                                <p>Home</p>
                            </a>
                            <a class="nav-link" asp-controller="Cotizador" asp-action="Index">
                                <i class="nav-icon fas fa-chart-line"></i>
                                <p>Cotizador Ventas</p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->

        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" id="mainContent">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 1.0.0
            </div>
            <strong>Copyright &copy; 2014-2021 <a href="#">Softwit Web</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- Modales -->
    <partial name="_LayoutModals" />

    <!-- jQuery -->
    <script src="~/lib/adminlte/plugins/jquery/jquery.min.js"></script>

    @*     <script src="~/lib/jquery/dist/jquery-3.7.1.js"></script>
    *@
    <!-- Bootstrap 4 -->
    <script src="~/lib/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/lib/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- Select2 -->
    <script src="~/lib/adminlte/plugins/select2/js/select2.full.min.js"></script>
    <script src="~/lib/adminlte/plugins/select2/js/i18n/es.js"></script>
    <!-- Bootstrap4 Duallistbox -->
    <script src="~/lib/adminlte/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
    <!-- InputMask -->
    <script src="~/lib/adminlte/plugins/moment/moment.min.js"></script>
    <script src="~/lib/adminlte/plugins/inputmask/jquery.inputmask.min.js"></script>
    <script src="~/lib/adminlte/plugins/moment/locale/es.js"></script>
    <!-- date-range-picker -->
    <script src="~/lib/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap color picker -->
    <script src="~/lib/adminlte/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/lib/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Bootstrap Switch -->
    <script src="~/lib/adminlte/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <!-- BS-Stepper -->
    <script src="~/lib/adminlte/plugins/bs-stepper/js/bs-stepper.min.js"></script>
    <!-- dropzonejs -->
    <script src="~/lib/adminlte/plugins/dropzone/min/dropzone.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/lib/adminlte/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/adminlte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/adminlte/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/lib/adminlte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/adminlte/plugins/datatables-select/js/datatables.select.min.js"></script>
    <script src="~/lib/adminlte/plugins/datatables-select/js/select.bootstrap4.min.js"></script>

    <!-- jquery-validation -->
    <script src="~/lib/adminlte/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/lib/adminlte/plugins/jquery-validation/additional-methods.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/lib/adminlte/dist/js/adminlte.min.js"></script>


    <script type="text/javascript">
        var baseSiteUrl = '@Url.Content("~/")';
    </script>
    <script src="~/js/app.js"></script>

    @await RenderSectionAsync("Scripts", required: false)


</body>









</html>

SoftkitWeb/Views/Shared/_LayoutMenuUserAccount.cshtml
@*@using Microsoft.AspNet.Identity

@if (User.Identity.IsAuthenticated)
{
    <li class="dropdown user user-menu">
        <!-- Menu Toggle Button -->
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="~/Content/img/user-256.png" class="user-image" alt="User Image" />
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">@User.Identity.GetUserName().ToUpper()</span>
        </a>
        <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
                <img src="~/Content/img/user-256.png" class="img-circle" alt="User Image" />
                <p>
                    <strong>@User.Identity.Name.ToUpper()</strong><br />
                    @if (User.Identity.GetUserId().Equals("1"))
                    {

                        <strong>Administrador  </strong>

                    }
                    else
                    {
                        <strong>Vendedor  </strong>
                    }
                </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
                <div class="row">

                </div>
                <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer"> 
                <div class="pull-right">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat">Cerrar sesi&oacute;n</a>
                    }
                </div>
            </li>
        </ul>
    </li>
}*@

SoftkitWeb/Views/Shared/_LayoutModals.cshtml
 <!-- Modal message -->
<div class="modal fade" id="modalMessage" tabindex="-1" role="dialog" aria-labelledby="titleModalMessage" aria-hidden="true">
    <div class="modal-dialog" role="document" id="dialogModalMessage">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="titleModalMessage"></h4>
            </div>
            <div class="modal-body" id="bodyModalMessage"></div>
            <div class="modal-footer" id="footerModalMessage">
                <button type="button" class="btn btn-sm btn-danger pull-left" data-dismiss="modal" id="btnCancelModalMessage"></button>
                <button type="button" class="btn btn-sm btn-success" data-dismiss="modal" id="btnAcceptModalMessage"></button>
            </div>
        </div>
    </div>
</div>
<!-- Modal error -->
<div class="modal modal-danger fade" id="modalError" tabindex="-1" role="dialog" aria-labelledby="titleModalError" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" id="dialogModalError">
        <div class="modal-content">
            <div class="modal-header pgm-message-danger" id="headerModalError">
                <h4 class="modal-title" id="titleModalError">Error</h4>
            </div>
            <div class="modal-body" id="bodyModalError"></div>
            <div class="modal-footer" id="footerModalError">
                <button type="button" class="btn btn-sm btn-default pull-left" data-dismiss="modal" id="btnAceptarModalError">Aceptar</button>
            </div>
        </div>
    </div>
</div>
<!-- Modal loading  -->
<div class="modal fade" id="modalLoading" tabindex="-1" role="dialog" aria-labelledby="titleModalLoading" aria-hidden="true">
    <div class="modal-dialog">
        <div class="bsp-loading" role="document">
            <i class="fas fa-sync-alt fa-spin fa-3x fa-fw" aria-hidden="true"></i>
            <h4 id="messageLoading">Procesando, por favor espere...</h4>
        </div>
    </div>

</div>